# Site settings
title: Vineet Pedaballe's github hosting
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This webpage is used to host links to important and useful github repos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vineetp
github_username:  vpedabal

# Build settings
markdown: kramdown
